#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr  3 23:48:38 2021

@author: arsi
"""

import pandas as pd

from tscfat.Analysis.calculate_similarity import calculate_similarity
	
# load a dataframe and convert the index to datetime
df = pd.read_csv('/home/arsi/Documents/tscfat/Data/one_subject_data.csv',index_col=0)
df.index = pd.to_datetime(df.index)

# convert one column to a numpy array
name = 'positive'
ser = df[name].values.reshape(-1,1)

sim = calculate_similarity(ser)
    
