#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 21 14:15:12 2020

@author: ikaheia1
"""


import matplotlib.pyplot as plt
import pandas as pd
from math import pi
 
# Set data
'''
df = pd.DataFrame({
'group': ['A','B','C','D'],
'var1': [38, 1.5, 30, 4],
'var2': [29, 10, 9, 34],
'var3': [8, 39, 23, 24],
'var4': [7, 31, 33, 14],
'var5': [28, 15, 32, 14]
})
'''
 
# number of variable
N = 24
M = 69 
# We are going to plot the first line of the data frame.
# But we need to repeat the first value to close the circular graph:
#values=df.loc[0].drop('group').values.flatten().tolist()

 
# What will be the angle of each axis in the plot? (we divide the plot / number of variable)
angles = [n / float(N) * 2 * pi for n in range(N)]
angles += angles[:1]

# 
fig = plt.figure(figsize=(10,10)) 
# Initialise the spider plot
ax = plt.subplot(111, polar=True)

for i in range(M): 

    if clusters[i] == 0:
        c = "red"
    else:
        c = "blue"

# Draw one axe per variable + add labels labels yet
#plt.xticks(angles[:-1], categories, color='grey', size=8)
    values = data[i].tolist()
    values += values[:1]
# Draw ylabels
#ax.set_rlabel_position(0)
#plt.yticks([10,20,30], ["10","20","30"], color="grey", size=7)
#plt.ylim(0,40)

# Plot data
    ax.plot(angles, values, linewidth=1, linestyle='solid',color=c)
 
# Fill area
#ax.fill(angles, values, 'b', alpha=0.1)