#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 21 13:56:55 2020

@author: ikaheia1
"""
import statsmodels.api as sm

def Plot_summary()df:
    df['battery_level'].describe()
    df['battery_level'].plot.hist(bins=20,grid=True,title="Battery level histogram")
    df['battery_level'].plot.box(grid=True,title="Battery level bar plot")
    pd.plotting.lag_plot(df.battery_level,lag=1)
    pd.plotting.autocorrelation_plot(df.battery_level).set_xlim([0,240])
    sm.graphics.tsa.plot_pacf(df.battery_level,lags=48)
    sm.graphics.tsa.plot_acf(df.battery_level,lags=24*7)
    return None


def Summary_statistics(df):
    
    Plot_summary(df)
    
    return None