#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 31 23:04:32 2021

@author: ikaheia1
"""

import pytest
import numpy as np

from tscfat.Utils import analysis_parameters

class TestAnalysisParameters(object):
    
    def test_calculate_distance(self):